{
 "title": "WebTours metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "WebTours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=", "value": "WebTours" }
     ]
    }
   ]
  },
  {
   "title": "Processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processor User Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host, $measurement, $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "select": [
        [
         { "params": [ "Percent_User_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% User Time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-V2M51UN" }
       ]
      }
     ]
    },
    {
     "title": "Processor Queue Length",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host, $measurement, $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_system",
       "select": [
        [
         { "params": [ "Processor_Queue_Length" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Processor Queue Length" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-V2M51UN" }
       ]
      }
     ]
    },
    {
     "title": "Processor Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host, $measurement, $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "select": [
        [
         { "params": [ "Percent_Processor_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Processor Time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-V2M51UN" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Committed Bytes In Use",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host, $measurement, $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Percent_Committed_Bytes_In_Use" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Committed Bytes In Use" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-V2M51UN" }
       ]
      }
     ]
    },
    {
     "title": "Avalible Bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host, $measurement, $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Available_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Avalible Bytes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-V2M51UN" }
       ]
      }
     ]
    },
    {
     "title": "Pages Faults per sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host, $measurement, $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Page_Faults_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Pages Faults/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-V2M51UN" }
       ]
      }
     ]
    },
    {
     "title": "Pages per sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host, $measurement, $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Pages_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Pages/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-V2M51UN" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Disk Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host, $measurement, $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "select": [
        [
         { "params": [ "Percent_Disk_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Disk Time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-V2M51UN" }
       ]
      }
     ]
    },
    {
     "title": "Current disk queue length",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host, $measurement, $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "select": [
        [
         { "params": [ "Current_Disk_Queue_Length" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Current disk queue length" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-V2M51UN" }
       ]
      }
     ]
    },
    {
     "title": "% Disk write time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host, $measurement, $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "select": [
        [
         { "params": [ "Percent_Disk_Write_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Disk write time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-V2M51UN" }
       ]
      }
     ]
    },
    {
     "title": "% Disk read time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host, $measurement, $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "select": [
        [
         { "params": [ "Percent_Disk_Read_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Disk read time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-V2M51UN" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes receved per sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host, $measurement, $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_net",
       "select": [
        [
         { "params": [ "Bytes_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Bytes receved/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-V2M51UN" }
       ]
      }
     ]
    },
    {
     "title": "Bytes sent per sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host, $measurement, $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_net",
       "select": [
        [
         { "params": [ "Bytes_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Bytes sent/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-V2M51UN" }
       ]
      }
     ]
    },
    {
     "title": "Packets",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host, $measurement, $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "win_net",
       "select": [
        [
         { "params": [ "Packets_Received_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Packets receved/sec" ], "type": "alias" }
        ],
        [
         { "params": [ "Packets_Sent_persec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Packets sent/sec" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "DESKTOP-V2M51UN" }
       ]
      }
     ]
    }
   ]
  }
 ]
}